name: Python CI

on:
  push:
    branches:
    - "master"
    - "dev"
  pull_request:
    branches:
    - "**"

jobs:
  run_tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        python-version:
        - "3.8"

    steps:
    - uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Start Elasticsearch
      run: make test.start_elasticsearch

    - name: Install pip
      run: pip install -r requirements/pip.txt

    - name: Install Dependencies
      run: |
        pip install -r requirements/ci.txt
        pip install -r requirements/testing.txt

    - name: Run Tests
      run: make test
